### ISSUE TITLE
MC 1.15 tracking issue

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage#2306]
- [x] Fix compiler errors
- [x] Restore functionality
- [x] Utilize new container system for some syncing cases (grid, crafter manager)
- [x] Rethink `Comparer` (maybe remove it and add "fuzzy compare" option)
- [x] Remove null-ability of item/fluid storage API in RS
- [x] Decouple `INetwork` from the Controller
- [x] Remove energy API
- [x] Rename classes to adapt to MCP naming convention (`BlockGrid` -> `GridBlock`, `Gui` -> `Screen`)
- [x] Reorganize packages (primarily API)
- [x] Rework GUIs
- [x] Use `ResourceLocation` for RS registries
- [x] Remove `@Deprecation`s
- [x] Re-add advancements
- [x] Fix Grid crafting/stack separation
- [x] Make `Style`s static
- [x] Rework build script to publish to Maven
- [x] Add helper for NetworkNodeProxy stuff
- [x] Port Wireless Crafting Grid addon
- [x] Fix issues relating to 1.14 changes on the issue tracker (#2315 & #2316)
- [x] Convert lang files
- [x] Update site for 1.15
- [x] Update supported versions for 1.15
- [x] Check out PRs
- [x] Take decision about mc1.12
- [x] Improve hitbox checking
- [ ] Check `@Volatile`s
- [ ] Remove unneeded null checks in GUI
- [ ] Fix network transmitter crossdim issues
- [ ] Add creator metadata to disks
- [ ] Fix remaining TODOs
- [ ] jar signing

**Comment by raoulvdberge** [comment]
Closed in favor of #2604
